name: uruti
description: Uruti - Digital Ecosystem for Founders and Investors
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  path_provider: ^2.1.3
  equatable: ^2.0.5
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-VariableFont_wght.ttf
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Uruti-BG.png"
  min_sdk_android: 21
  adaptive_icon_background: "#76B947"
  adaptive_icon_foreground: "assets/images/Uruti-BG.png"